### ISSUE TITLE
Integration: 16 - Plugin implement DocumentService

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#123]
## Details

There are existing 2 different scenarios:
1. It's possible for some ERP system to upload the binary of a file to the system like SAP or ProALpha.
1. For other ERP systems, the customer wants usually the files like PDF copied to a network path.

## ToDo - scenario 1

+ [ ] Implement the `Create` for the DocumentService _(check if create really needed, this means create document without binary)_
+ [ ] Implement the `QUERY` for the DocumentService
+ [ ] Implement the `UPDATE` for the DocumentService
+ [ ] Implement the `Download` for the DocumentService
+ [ ] Implement the `Upload` for the DocumentService

## ToDo - scenario 2

+ [ ] Delete the document service
+ [ ] Implement directly in the powerJobs the copy to the network path
  + [ ] If needed transfer also metadata like Description, Creater with the given protocol, for instance, a text file
