### ISSUE TITLE
Create a sample c# Console Application for ERP Team

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#134]
### UserStory

As a powerGate Project developer, I want to receive a working sample application which consumes the ERP API and ensures the basic functionality for the powerGate template, so that I don't investigate much time to test if the ERP API is working as expected.

### Workflow

For a .Net ERP SDK we ask for a sample console application.
The ERP Team delivers this application always in different ways and usually not in a way that all our functionality defined in #97 is tested.

### Task

+ [ ] Create a sample console application which consumes our interface #126 
+ [ ] Upload the source code to Github Code and attach it to the plugin solution
  + The installer should not install this project of the console
  + [ ] This project should be successfully be built on the pipeline
  + [ ] Link the github source to #97 that everybody can download directly this sample application and replace it with their ERP API
  + [ ] Explain how to clone and push the new code, then the ERP Team directly changes in GitHub on a new branch to ensure that the master is not broken

**Comment by PatrickGrub** [comment]
See branch Issue-134, implementation:
+ [X] Item tests
+ [ ] Bom tests
+ [ ] Documents tests

**Comment by georgschwienbacher** [comment]
eingeplant für Dienstag 23.03

**Comment by marcomirandola** [comment]
@PatrickGrub, ich habe das Gefühl, dass wir das Problem größer machen als notwendig. Zwei Dinge wollen wir hier erreichen:
1. die einzelnen powerGate API calls testen und damit die ERP API. Das ist unser klassische PowerShell Test-Script. das hat sich bewährt, ist einfach und kann dann von den Client-Entwickler verwendet werden um die Client Seite zu implementieren
2. wir wollen einen rudimentären Performance Test machen. Dazu sollen in einer Schleife 100 Artikel angelegt werden, diese dann gelesen werden und dann noch aktualisiert werden. Dazu sollen mit den erzeugten Artikel, 10 Stücklisten a ca. 90 Positionen angelegt werden, und diese dann wieder ausgelesen. Die Zeiten werden erfasst und dem Kunden mitgeteilt.

Damit haben wir einen einfachen Script wo die Liste der Befehle für das Projekt erfasst sind, und eine Zeiterfassung der Grundaktionen.

Das wird ein Mal gemacht, und nie wieder. Daher braucht es keine Unitest, kein Pestor, keine komplexen Oberflächen. Einfach ein Script.
