### ISSUE TITLE
Create a sample postman collection for the ERP Team

### ISSUE THREAD

**Issue by PatrickGrub** [coolOrangeLabs/powerGateTemplate#135]
### UserStory

As a powerGate Project developer, I want to receive a working sample application which consumes the ERP **webservice** API and ensures the basic functionality for the powerGate template, so that I don't investigate much time to test if the ERP API is working as expected.

### Workflow

For an ERP webservice API we ask for a postman collection.
The ERP Team delivers this collection always in different ways and usually not in a way that all our functionality defined in #97 is tested.

### Task

+ [x] Create a sample postman collection which consumes our interface #126 
  + [ ] Use [postman tests](https://learning.postman.com/docs/postman/scripts/test-examples/) to ensure the body, header.. is as expected
+ [x] Make this collection easy sharable, maybe make it public?
  + [ ] Link it to #97 that everybody can download directly this sample application and replace it with their ERP API

**Comment by PatrickGrub** [comment]
Discussed today with @KonradLeutenmayr and this would be very helpful for new offers where a customer implements a new Webservice for us.

@georgschwienbacher can this be planned after my vacation?

**Comment by georgschwienbacher** [comment]
für 27.09 eingeplant

**Comment by PatrickGrub** [comment]
Created postman colleciton:
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/449025-2a87fae5-a69a-44fa-b87e-8543f21a7688?action=collection%2Ffork&collection-url=entityId%3D449025-2a87fae5-a69a-44fa-b87e-8543f21a7688%26entityType%3Dcollection%26workspaceId%3Dada86f7b-de1a-46bd-9f82-5c9689139a8d)

Preperared:
+ [X] Items
+ [ ] Boms (Missing 1h)
+ [ ] Documents (Missing 1h)

**Comment by PatrickGrub** [comment]
Created all webservice examples and added new WIKI and extended #97
https://github.com/coolOrangeLabs/powerGateTemplate/wiki/API-Examples-for-ERP

Forwarded wiki page internally to improve future communication with ERP teams.
