### ISSUE TITLE
Initial Checks: Delivery of NAV API sample calls + documentation

### ISSUE THREAD

**Issue by georgschwienbacher** [coolOrangeLabs/powerGateTemplate#196]
# Tasks for the ERP Teams

## Requirements

1. Connection strings for development, test, and production environment
1. API with the below-mentioned functions
   1. The ERP developer **must** read [this page](https://github.com/coolOrangeLabs/powerGateTemplate/wiki/API-Examples-for-ERP). Please forward it to the responsible ERP developer!
1. API documentation
1. API sample application

#### What kind of API?

The ERP to Vault integration is implemented with C# (.Net) as a powerGate Server plugin by coolOrange.

As communication technology we ask for:
+ An SDK for .Net (preferred)
  + For C# we have an **interface** that we have provided for you, [read details here!](https://github.com/coolOrangeLabs/powerGateTemplate/wiki/ERP-C%23-API)
+ REST Webservices to receive and send data from/to the ERP system
+ Database access through stored procedures and views 

### API minimum functions

Following functions are required:

#### Items
- Create a new ERP item
  - Optional: Generating a new number based on an ERP numbering scheme
- Update an existing ERP item
- Read one ERP item
- Search multiple ERP items with search criteria such as “contains”

#### Bill of Materials
- Create a new Bill of Material (only first level)
- Update Bill of Material header information
   - Delete one ERP item from the existing Bill of Material
   - Update one ERP item of the existing Bill of Material
- Read one Bill of Material header with Bill of Material positions (only first level)

#### Documents
- Upload a document to the ERP system as a binary
- Update the metadata of a document in the ERP system
- Update the document binary in the ERP system
- Read the metadata of a document in the ERP

____________________________

#### NAV Specific Webservices needed for standard implementation
| Functionality | Object ID  | Name |
| - | - | - |
| Items | 30 | Item Card |
| Bill of Materials | 99000786 | Production BOM Card |
| Documents | 447 | Record Link Management |

#### Advanced Functionality
| Functionality | Object ID  | Name |
| - | - | - |
| Version in BOM* | 99000809 | Production BOM Version |
| Extended Texts** | 386 | Extended Texts |
| all Vendors | 27 | Vendor List |
| Vendor details | 26 | Vendor Card |

- '* `Production_BOM_No` as property needs to be activated in the web services
- ** `TableName` as property needs to be activated in the web services
- ** `No` as property needs to be activated in the web services

___________________________

### API documentation 

Independently from the API type, we need API documentation for instance a word file.

### API sample application 

We need a sample application provided by the ERP team in order to ensure that the provided API works as expected.

All the required API functions _(see above)_ and authentication must be shown, depending on the API type:
+ For web services, a [Postman Collection](https://www.getpostman.com/collection)
+ For a .NET SDK, a sample console application

#### Disclaimer

- The resources requested above are prerequisites for the continuation of the project
- The resources have to be provided by the ERP department of the customer/the ERP contractor of the customer as requested above. 
- The project budget available to coolOrange only includes the handover meeting between the ERP side to coolOrange. 
- In the handover meeting, the ERP department/contractor will present to coolOrange how to call each API function with a sample call, the same applies to the authentification. The presentation has to be made in the test environment provided by the customer. 
- Any further engagement on coolOrange side to get the ERP API ready for implementation is **not** part of the project budget.

# coolOrange Tasks

+ [ ] Verify the received sample application from the ERP Team for instance in a Meeting. _If we need to create the sample application then read "Initial Checks: ERP API Performance" to understand the best way for an test application"_
  + [ ] mimic the customer workflow discussed with the API calls and verify the data in the ERP system
  + [ ] Comment test result here as comment
  + [ ] Write wiki about special and important behaviors
  + If an example is missing or something not worked as expected then the ERP team must prove that the API works
+ [ ] Copy a Plugin template for this ERP. For instance if a new ERP with REST service is used then search for reference in the [internal wiki for templates](https://github.com/coolOrangeProjects/NuGet_Packages/wiki)
+ [ ] Upload all resources to Github
+ [ ] Start with the implementation of the integration issues by asking the Project Management
