### ISSUE TITLE
Kundentests - VAULT Stammdaten

### ISSUE THREAD

**Issue by AlexQua** [coolOrangeLabs/powerGateTemplate#71]
# ToDo:
- **Update all wiki links when moving to a customer repo!**
---

### Test Ziel

Überprüfen Sie die Ansicht des Bereichs Vault auf **STAMMDATEN** Das heißt:

###  Testabschnitte

+ [ ] ERP ITEM Tab:

   + [ ] Neuanlage ([_Neuanlage Wiki_](https://github.com/coolOrangeProjects/Conti-Machinery/wiki/Neuanlage#sap-artikel-erstellung))
   + [ ] Aktualisierung ([_Aktualisireung Wiki_](https://github.com/coolOrangeProjects/Conti-Machinery/wiki/Neuanlage#sap-artikeln-aktualisierung))

---

+ [ ] ERP SEARCH Tab [Wiki Vault Suche](https://github.com/coolOrangeProjects/Conti-Machinery/wiki/Suche#vault-stammdaten):

   + [ ] Suchen
   + [ ] Verknüpfen

---

### Ergebnis
+ Erfolgreich => `getestet & abgenommen` label setzen

+ Fehler => Schreiben Sie unter diesen Kommentar einen neuen, der das Problem beschreibt.
Markieren Sie dabei den zuständigen Entwickler (Programmier-fragen) oder Projekt Manager (Verwaltungsfragen) mit @NameDesEntwicklers für das jeweilige Problem.
