### ISSUE TITLE
Kundentests - VAULT BOMs

### ISSUE THREAD

**Issue by AlexQua** [coolOrangeLabs/powerGateTemplate#73]
# ToDo:
- **Update all wiki links when moving to a customer repo!**
---

### Test Ziel

Überprüfen Sie den **_BOM Workflow_** (für beide **Dateien** und **Stammdaten**).

### Schnittstelle

![BOM and ERP BPOM](https://user-images.githubusercontent.com/43955487/59937330-756fc880-9452-11e9-94d8-e752b8331049.PNG)

### Testabschnitte

+ [ ] BOM Window [coolOrange official wiki](https://www.coolorange.com/wiki/doku.php?id=powergate:bom_window)
   + Artikel: 
      + [ ] [Artikel Prüfen](https://github.com/coolOrangeProjects/Conti-Machinery/wiki/St%C3%BCcklisten-Dialog#pr%C3%BCfen)
      + [ ] [Artikel Übermitteln](https://github.com/coolOrangeProjects/Conti-Machinery/wiki/St%C3%BCcklisten-Dialog#%C3%9Cbermitteln)
   + Stückliste: 
      + [ ] [Stückliste Prüfen](https://github.com/coolOrangeProjects/Conti-Machinery/wiki/St%C3%BCcklisten-Dialog#pr%C3%BCfen-1)
      + [ ] [Stückliste Übermitteln](https://github.com/coolOrangeProjects/Conti-Machinery/wiki/St%C3%BCcklisten-Dialog#%C3%9Cbermittelen)

---

+ [ ] ERP ITEM Tab:
   + [ ] Lesen des BOMs

---

### Ergebnis
+ Erfolgreich => `getestet & abgenommen` label setzen

+ Fehler => Schreiben Sie unter diesen Kommentar einen neuen, der das Problem beschreibt. Markieren Sie dabei den zuständigen Entwickler (Programmier-fragen) oder Projekt Manager (Verwaltungsfragen) mit @NameDesEntwicklers für das jeweilige Problem.
