### ISSUE TITLE
Kundentests - INVENTOR

### ISSUE THREAD

**Issue by AlexQua** [coolOrangeLabs/powerGateTemplate#74]
# ToDo:
- **Update all wiki links when moving to a customer repo!**
---

### Test Ziel

Überprüfen Sie die Inventor Schnittstelle für die _Neuanlage_ und _Aktualisierung_ von ERP Artikeln

### Zugriff auf zugehörige _Tabs_

![Inventor](https://user-images.githubusercontent.com/43955487/59936870-57559880-9451-11e9-9f58-68245215e95d.PNG)

###  Testabschnitte

+ [ ] `SAP` Tab

  + [ ] [Neuanlage](https://github.com/coolOrangeProjects/Conti-Machinery/wiki/Neuanlage-Inventor#neuanalge)
  + [ ] [Aktualisierung](https://github.com/coolOrangeProjects/Conti-Machinery/wiki/Neuanlage-Inventor#anzeige-von-existierenden-artikel---aktualisierung)

---

+ [ ] `ERP Suche` Tab

  + [ ] [`Suche` und `Verknüpfen`](https://github.com/coolOrangeProjects/Conti-Machinery/wiki/Suche-Inventor#suchen)
  + [ ] [`Einsetzen`](https://github.com/coolOrangeProjects/Conti-Machinery/wiki/Suche-Inventor#virtuelles-teil-einf%C3%BCgen) (nur für _Baugruppe_)

---

### Ergebnis
+ Erfolgreich => `getestet & abgenommen` label setzen

+ Fehler => Schreiben Sie unter diesen Kommentar einen neuen, der das Problem beschreibt. Markieren Sie dabei den zuständigen Entwickler (Programmier-fragen) oder Projekt Manager (Verwaltungsfragen) mit @NameDesEntwicklersfür das jeweilige Problem.
