### ISSUE TITLE
Kundentests - Dokumente

### ISSUE THREAD

**Issue by AlexQua** [coolOrangeLabs/powerGateTemplate#75]
# ToDo:

- **Update all wiki links when moving to a customer repo!**
---

## Test Ziel

Um zu testen, ob der PDF-Export für das des Dokuments (`.idw`, `.dwg`) durchgeführt wird, wenn der Dokumentenstatus auf `Release` wechselt, und um zu prüfen, ob die Dokumente dann korrekt in das ERP-System hochgeladen werden.

## Schnelle Einführung in PowerJobs

* PowerJobs wird verwendet, um die Aufträge auszuführen, die sich um den PDF-Export kümmern. Es verwendet den Vault Job Processor.

* Wenn der Jobprozessor frei ist und der Job bearbeitet wird, erfolgt ein Export der Zeichnung nach PDF. Die Jobs laden es auch in das ERP hoch.

#### Prozess

* Wenn der Zeichnungszustand auf Freigabe wechselt, wird ein Auftrag in die Warteschlange aufgenommen.

![State_Change_Trigger_Job](https://user-images.githubusercontent.com/43955487/64510167-c7055200-d2e1-11e9-9da0-2576fbe2a310.PNG)

* Um zu sehen, ob ein Auftrag zur Warteschlange hinzugefügt wurde, kann dies direkt über Vault erfolgen:

![image](https://user-images.githubusercontent.com/43955487/65878558-a71bf800-e38e-11e9-949d-11f1e7554164.png)

**Deutsch**: _Main menu > Extras > Warteschleife_ // **English**: _Main Menu > Tools > Job-Queue_

* Sobald sich der Auftrag in der Warteschlange befindet, bedeutet dies, dass PowerJobs verarbeitet wird (nachdem alle vorherigen Aufträge bearbeitet wurden). Wenn PowerJobs geöffnet ist, werden einige Protokolle bereits in der Anwendung angezeigt:

![image](https://user-images.githubusercontent.com/43955487/65873493-8601da00-e383-11e9-9192-c58ad606dc89.png)

* Wenn jedoch weitere Informationen benötigt werden, können die gesamten _Logs_ überprüft werden:

  `C:\Benutzer\ {Benutzername} \AppData\Local\coolOrange\powerJobs\Logs\powerJobs.log`

 * Wenn weitere Fragen auftauchen, finden Sie weitere Informationen auf der [official PowerJobs wiki](https://www.coolorange.com/wiki/doku.php?id=powerjobs)

---

## Testabschnitte

+ [ ] Nach dem Zustandswechsel der Zeichnung auf `Freigabe` wird der Prüfauftrag in die Auftragswarteschlange aufgenommen.

+ [ ] Öffnen Sie PowerJobs und überprüfen Sie die dort angezeigten _Logs_ . Überprüfen Sie, ob kein Fehler ausgelöst wird.

+ [ ] Nachdem der Auftrag abgeschlossen ist, überprüfen Sie in Vault, ob das PDF hinzugefügt und auch an die übergeordnete Zeichnung angehängt wurde.

+ [ ] Das PDF wurde in das ERP hochgeladen (Pfad oder Datei selbst).

---

### Ergebnis
+ Erfolgreich => `getestet & abgenommen` label setzen

+ Fehler => Schreiben Sie unter diesen Kommentar einen neuen, der das Problem beschreibt. Markieren Sie dabei den zuständigen Entwickler (Programmier-fragen) oder Projekt Manager (Verwaltungsfragen) mit @NameDesEntwicklersfür das jeweilige Problem.
