### ISSUE TITLE
2 - Setting Azure Pipeline

### ISSUE THREAD

**Issue by AlexQua** [coolOrangeLabs/powerGateTemplate#76]
## Description
Set the Azure Pipeline for the project. For the detailed guide, go in Teams: [Azure Pipeline Wiki](https://teams.microsoft.com/l/channel/19%3A5caadbfba9224cc5813b8f6dd96495cc%40thread.skype/tab%3A%3A12884ff2-e23f-43b0-9926-c1061c185ce3)

# ToDo

+ [ ] Create new Build Pipeline
+ [ ] Adapt the default YML file
+ [ ] Create Release pipeline
+ [ ] Create and assign Variable Group to both Build & Release
+ [ ] Add the Status Badge in the Readme.md
