### ISSUE TITLE
Preparation of a test environment

### ISSUE THREAD

**Issue by AlexQua** [coolOrangeLabs/powerGateTemplate#99]
all coolOrange products can be downloaded here: [coolOrange Download Portal](http://download.coolorange.com/)
Test licenses will be provided by coolOrange for the duration of the project until Go Live. coolOrange products can run up to 30 days in trial mode. Activation with project license will be done by coolOrange team. For the duration of the project the test environment may only be used for the Vault to ERP integration project.

alle coolOrange Produkte können hier heruntergeladen werden: [coolOrange Download Portal](http://download.coolorange.com/)
Test-Lizenzen werden von coolOrange für die Laufzeit des Projektes zur Verfügung gestellt. Alle coolOrange Produkte können für 30 Tage kostenfrei getestet werden. Die Aktivierung wird durch einen coolOrange Mitarbeiter durchgeführt. Für die Dauer des Projektes sollte die Testumgebung nur für das Vault-ERP Integrationsprojekt verwendet werden.

## Server
- [ ] Operating System: see [powerGate Server Installation Requirements](https://www.coolorange.com/wiki/doku.php?id=powergateserver:installation#requirements)
- [ ] Hardware: Identical to the Vault Server Hardware recommendations
- [ ] dedicated Autodesk Vault Vault (test database)
- [ ] .Net Framework 4.7 or higher
- [ ] Windows User with local Administrator rights
  - if Administrator user is not possible minimum requirements are
    - [ ] Read/Write Permission for `C:\ProgramData\coolOrange\`
    - [ ] Read/Write Permission for `C:\ProgramData\Autodesk\`
    - [ ] Permission to install/execute Windows Services (Background: [powerGate Documentation](https://www.coolorange.com/wiki/doku.php?id=powergateserver:installation#windows_permissions))
### Tasks for coolOrange
`prerequisites: coolOrange user with installation permissions`
- [ ] [coolOrange powerGateServer](https://www.coolorange.com/wiki/doku.php?id=powergateserver:installation)
- [ ] [Pester](https://github.com/pester/Pester/wiki) v4 or higher
- [ ] [Telerik Fiddler](https://www.telerik.com/download/fiddler)
- [ ] [Visual Studio Code](https://code.visualstudio.com/Download)

## Client

- [ ] Operating System: see [powerGate Installation Requirements](https://www.coolorange.com/wiki/doku.php?id=powergate:installation#requirements)
- [ ] Hardware: Identical to a CAD workstation
- [ ] PowerShell 4.0 or higher
- [ ] Windows User with local Administrator rights
- [ ] Autodesk Vault Workgroup/Professional Client 
- [ ] Vault User (user permissions)
- [ ] Autodesk Datastandard for Vault Workgroup/Professional
- [ ] Autodesk Inventor Professional
- [ ] Autodesk Datastandard for Inventor Professional
- [ ] ERP Client Software 
- [ ] ERP Client User + Passowrd (user permissions)
### Tasks for coolOrange
`prerequisites: coolOrange user with installation permissions`
- [ ] [coolOrange powerVault](https://www.coolorange.com/wiki/doku.php?id=powervault)
- [ ] [coolOrange powerGate Client](https://www.coolorange.com/wiki/doku.php?id=powergate:installation)
- [ ] [Telerik Fiddler](https://www.telerik.com/download/fiddler)
- [ ] [Visual Studio Code](https://code.visualstudio.com/Download)

#### Developer/Support Task

- [ ] Changing Connect-ERP
- [ ] Verify connection to ERP
- [ ] Installing powerGateStandard setup
- [ ] Change the PowerShell files in the Data Standard Folder and save in order to check permissions
